---
- name: Fallar si intenta instalar OpenJDK en SLES 11
  fail:
    msg: "OpenJDK no está disponible ni es compatible con SLES 11."
  when: java == "openjdk" and ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 11

- name: Instalar OpenJDK
  package:
    name: "{{ openjdk_package }}"
    update_cache: yes
    state: present
  when: java == "openjdk"

- block:
    - name: Crear el directorio {{ oraclejdk_options.base_folder }}
      file:
        path: "{{ oraclejdk_options.base_folder }}"
        state: directory

    - name: Extraer el tarball de Oracle JDK
      unarchive:
        src: "{{ oraclejdk_options.tarball_location }}"
        dest: "{{ oraclejdk_options.base_folder }}"
        owner: root
        group: root
        mode: 0755
        remote_src: "{{ oraclejdk_options.remote_files }}"
        list_files: yes
        keep_newer: yes
      register: tarball_content

    - name: Establecer el nuevo nombre de la carpeta JDK
      set_fact:
        jdk_folder: "{{ tarball_content.files[0] | regex_replace('/(.*)$','') }}"

    - name: Crear el symlink {{ oraclejdk_options.base_folder }}/latest
      file:
        src: "{{ oraclejdk_options.base_folder }}/{{ jdk_folder }}"
        path: "{{ oraclejdk_options.base_folder }}/latest"
        state: link
        force: yes

    - name: Extraer el archivo JCE
      unarchive:
        src: "{{ oraclejdk_options.jce_location }}"
        dest: "{{ oraclejdk_options.base_folder }}/latest/jre/lib/security"
        owner: root
        group: root
        mode: 0755
        remote_src: "{{ oraclejdk_options.remote_files }}"

    - name: Copiar el archivo jar JCE a {{ oraclejdk_options.base_folder }}/latest/jre/lib/security
      copy:
        src: "{{ oraclejdk_options.base_folder }}/latest/jre/lib/security/UnlimitedJCEPolicyJDK8/{{ item }}"
        dest: "{{ oraclejdk_options.base_folder }}/latest/jre/lib/security"
        force: yes
        remote_src: yes
      with_items:
        - local_policy.jar
        - US_export_policy.jar
  when: java == "oraclejdk"
