---
- name: Crear la {{ db_name }} database ({{ database }})
  mysql_db:
    name: "{{ db_name }}"
    encoding: "{{ db_encoding | default(omit) }}"
    state: present

- name: Crear el usuario database {{ db_username }} y acceso basado en host ({{ database }})
  mysql_user:
    name: "{{ db_username }}"
    host: "{{ hostvars[item]['ansible_fqdn'] }}"
    priv: "{{ db_name }}.*:ALL"
    password: "{{ db_password }}"
    state: present
  with_items: "{{ db_client_hosts }}"

- name: Configurar el acceso basado en IP para el {{ db_username }} user ({{ database }})
  include_tasks: mysql_play_db_access.yml
  with_items: "{{ db_client_hosts }}"
