---
packages:
  - openssh-clients         # scp requerido por Ambari
  - curl                    # curl requerido por Ambari
  - unzip                   # unzip requerido por Ambari
  - tar                     # tar requerido por Ambari
  - wget                    # wget requerido por Ambari
  - openssl                 # openssl requerido por Ambari
  - chrony                  # ntp requerido por Hadoop
  - openssl-devel           # openssl-devel recommended for Ranger KMS
  - libtirpc-devel          # libtirpc requerido por HDP 2.6+
  - libselinux-python       # libselinux-python requerido por Ansible

openjdk_package: java-1.8.0-openjdk-devel

ntp_service_name: chronyd

firewall_service_name: firewalld

update_grub_command: 'grub2-mkconfig -o "$(readlink -n /etc/grub2.cfg)"'
