---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: (ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7) or (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 12)

- name: Reiniciar ambari-agent
  service:
    name: ambari-agent
    state: restarted

- name: Reiniciar ambari-server
  service:
    name: ambari-server
    state: restarted
  notify: "Esperar a que Ambari Server comience a escuchar en el puerto 8080"

- name: Esperar a que Ambari Server comience a escuchar en el puerto 8080
  wait_for:
    port: 8080
    host: 0.0.0.0
    delay: 1
