---
- block:
    - name: Establecer los permisos correctos para el secret key http
      file:
        path: /etc/security/http_secret
        owner: hdfs
        group: hadoop
        mode: 0440
  when: security != "none" and security_options.http_authentication|default(false) and install_hdp is defined and install_hdp
