---
- import_playbook: "set_variables.yml"

- name: Reunir datos de todos los nodos
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes

- import_playbook: "revisar_blueprint_dinamico.yml"
  when: blueprint_file == 'blueprint_dynamic.j2'

- name: Aplicar el rol ambari-config al grupo ambari-server
  hosts: ambari-server
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-config
