---
- import_playbook: "preparar_nodos.yml"
  tags: preparar_nodos

- import_playbook: "instalar_ambari.yml"
  tags: ambari

- import_playbook: "configurar_ambari.yml"
  tags: ambari,blueprint

- import_playbook: "aplicar_blueprint.yml"
  tags: blueprint

- import_playbook: "post_instalacion.yml"
  tags: post_instalacion
