---
- name: Cargar variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../ambari-server/vars

- name: Instalar paquete ambari-server
  package:
    name: ambari-server
    update_cache: yes
    state: latest
  notify: Reload systemd

- meta: flush_handlers

- block:
    - name: Instalar paquetes necesarios de mysql (para hive embedded)
      package:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items: "{{ mysql_packages | join(',') }}"

    - block:
        - name: Instalar mysql-server en Ubuntu 16 (para hive embedded)
          apt:
            name: 'mysql-server'
            update_cache: yes
            state: present

        - name: Configurar mysql para escuchar en todas las interfaces (Ubuntu 16)
          ini_file:
            path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
            create: no
            section: 'mysqld'
            option: 'bind-address'
            value: '*'
            no_extra_spaces: yes
            state: present
      when: ansible_distribution|lower == "ubuntu" and ansible_distribution_major_version|int == 16
      run_once: true
      delegate_to: "{{ hiveserver_hosts[0] }}"

    - name: Configurar el driver JDBC mysql para Ambari (para hive embedded)
      shell: /usr/sbin/ambari-server setup --jdbc-db=mysql --jdbc-driver={{ mysql_jdbc_location }}
      notify: Reiniciar ambari-server
  when: database == "embedded" and hiveserver_hosts is defined and hiveserver_hosts|length > 0

- block:
    - name: Instalar {{ database }} paquetes requeridos
      package:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items: "{{ lookup('vars', database + '_packages') | join(',') }}"

    - block:
        - name: Cargar el schema de Ambari Server (postgres)
          postgresql_db:
            name: "{{ database_options.ambari_db_name }}"
            maintenance_db: "{{ database_options.ambari_db_name }}"
            login_host: "{{ database_options.external_hostname|default(ansible_fqdn,true) }}"
            port: "{{ postgres_port }}"
            login_user: "{{ database_options.ambari_db_username }}"
            login_password: "{{ database_options.ambari_db_password }}"
            state: restore
            target: /var/lib/ambari-server/resources/Ambari-DDL-Postgres-CREATE.sql
          when: ansible_os_family|lower != "suse"

        - block:
            - name: Crear un .pgpass file (SUSE)
              template:
                src: pgpass.j2
                dest: /tmp/.pgpass-ambari
                mode: 0600
                force: yes

            - name: Verificar si el esquema de postgres ya se cargó (SUSE)
              shell: "PGPASSFILE=/tmp/.pgpass-ambari psql -h {{ database_options.external_hostname|default(ansible_fqdn,true) }} -U {{ database_options.ambari_db_username }} -p {{ postgres_port }} -w -d {{ database_options.ambari_db_name }} -c 'select user_id from ambari.users limit 0;'"
              register: check_results
              ignore_errors: true

            - name: Cargar el schema postgres de Ambari Server (SUSE)
              shell: "PGPASSFILE=/tmp/.pgpass-ambari psql -h {{ database_options.external_hostname|default(ansible_fqdn,true) }} -U {{ database_options.ambari_db_username }} -p {{ postgres_port }} -w -d {{ database_options.ambari_db_name }} < /var/lib/ambari-server/resources/Ambari-DDL-Postgres-CREATE.sql"
              when: check_results is failed

            - name: Eliminar el archivo .pgpass (SUSE)
              file:
                path: /tmp/.pgpass-ambari
                state: absent
          when: ansible_os_family|lower == "suse"
      when: database == "postgres"

    - block:
        - name: Cargar el schema de Ambari Server (mysql)
          mysql_db:
            name: "{{ database_options.ambari_db_name }}"
            login_host: "{{ database_options.external_hostname|default(ansible_fqdn,true) }}"
            login_port: "{{ mysql_port }}"
            login_user: "{{ database_options.ambari_db_username }}"
            login_password: "{{ database_options.ambari_db_password }}"
            state: import
            target: /var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql
          register: import_results
          ignore_errors: true

        - name: Fallar si no se pudo cargar el esquema mysql
          fail:
            msg: No se pudo cargar el esquema. El error es {{ import_results.msg }}!
          when: import_results is failed and not import_results.msg is search("Table .* already exists")
      when: database == "mysql" or database == "mariadb"

    - name: Configurar JDBC driver en Ambari
      shell: /usr/sbin/ambari-server setup --jdbc-db={{ database | regex_replace('mariadb', 'mysql') }} --jdbc-driver={{ lookup('vars', database + '_jdbc_location') }}
      notify: Reiniciar ambari-server

    - name: Establecer las opciones de configuración de la base de datos del servidor Ambari
      set_fact:
        ambari_database_options: "--database={{ database | regex_replace('mariadb', 'mysql') }} \
                                  --databasehost={{ database_options.external_hostname|default(ansible_fqdn,true) }} \
                                  --databaseport={{ lookup('vars', database | regex_replace('mariadb', 'mysql') + '_port') }} \
                                  --databasename={{ database_options.ambari_db_name }} \
                                  --databaseusername={{ database_options.ambari_db_username }} \
                                  --databasepassword={{ database_options.ambari_db_password }}"
  when: database != "embedded"

- name: Establecer la opción de configuración Java del Ambari server (OpenJDK)
  set_fact:
    ambari_java_options: "-j {{ openjdk_path }}"
  when: java == "openjdk"

- name: Establecer la opción de configuración Java del Ambari server (Oracle JDK)
  set_fact:
    ambari_java_options: "-j {{ oraclejdk_options.base_folder }}/latest"
  when: java == "oraclejdk"

- name: Actualizar la URL de descarga de Java embebido
  lineinfile:
    dest: /etc/ambari-server/conf/ambari.properties
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^(jdk.*\.jcpol-url)=(.*)/ARTIFACTS/(.*)', line: '\g<1>={{ repo_base_url }}/ARTIFACTS/\g<3>' }
    - { regexp: '^(jdk.*\.url)=(.*)/ARTIFACTS/(.*)', line: '\g<1>={{ repo_base_url }}/ARTIFACTS/\g<3>' }
  when: java == 'embedded'

- name: Ejecutar el setup del Ambari server
  shell: /usr/sbin/ambari-server setup -s {{ ambari_java_options|default("") }} {{ ambari_database_options|default("") }}
  notify: Reiniciar ambari-server

- name: Actualizar directorio log de ambari-server
  lineinfile:
    dest: /etc/ambari-server/conf/log4j.properties
    regexp: '^ambari.log.dir='
    line: 'ambari.log.dir={{ base_log_dir }}/ambari-server'
  notify: Reiniciar ambari-server

- name: Aumentar el tiempo de espera de startup del Ambari server
  lineinfile:
    path: /etc/ambari-server/conf/ambari.properties
    state: present
    line: 'server.startup.web.timeout=120'
  notify: Reiniciar ambari-server

- meta: flush_handlers

- name: Asegurar que inicie el servicio ambari-server
  service:
    name: ambari-server
    state: started

- name: Asegurar que el servicio ambari-server este enabled
  service:
    name: ambari-server
    enabled: yes
  ignore_errors: true
